---
deployment:
  tasks:
    - export DEPLOYPATH=/home1/edjuni41/nano.waveenterprise.com.br/
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R index.php actions.php deploy.php $DEPLOYPATH
    - /bin/cp -R lib views assets sql $DEPLOYPATH
    - /bin/cp .htaccess $DEPLOYPATH
    - /bin/cp .user.ini $DEPLOYPATH
    - /bin/mkdir -p $DEPLOYPATH/uploads/carros
    - /bin/chmod -R 755 $DEPLOYPATH/uploads
